language: php

php:
  - 5.3
  - 5.4
  - 7.0

sudo: false

env:
  - DB=MYSQL CORE_RELEASE=3.3

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.3
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss
  - composer install

script:
  - vendor/bin/phpunit crazy-egg/tests

branches:
  only:
    - master